// Programs are grouped by campus, then by degree/qualification level.
// Sourced from each university's official admissions pages (July 2026).
// BA "bouquet" combination degrees (Legon, KNUST) are listed as single
// subjects rather than every possible 3-subject combination, since the
// combinations run into the thousands and aren't meaningfully distinct
// as feed categories.

export const CAMPUS_PROGRAMS: Record<string, Record<string, string[]>> = {
  GCTU: {
    BSc: [
      "Information Technology",
      "Mobile Computing",
      "Information Systems",
      "Computer Science",
      "Computer Science (Cyber Security Option)",
      "Data Science and Analytics",
      "Networking and Systems Administration",
      "Software Engineering",
      "Internet of Things and Big Data",
      "Web Application Development",
      "Telecommunication Engineering",
      "Computer Engineering",
      "Electrical and Electronics Engineering",
      "Mathematics",
      "Actuarial Science with Data Analytics",
      "Computational Statistics",
      "Accounting with Computing",
      "Economics",
      "Procurement and Logistics",
      "E-Commerce and Marketing Management",
      "Financial Technology",
      "Business Administration (Banking and Finance)",
      "Business Administration (Human Resource Management)",
      "Business Administration (Marketing)",
      "Business Administration (Accounting)",
      "Business Administration (Management)",
    ],
    Diploma: [
      "Information Technology",
      "Cyber Security",
      "Computer Science",
      "Web Application Development",
      "Multimedia Technology",
      "Data Science and Analytics",
      "Telecommunications Engineering",
      "Computational Statistics",
      "Public Relations",
      "Administration (Management Option)",
      "Administration (Accounting Option)",
      "Administration (Marketing Option)",
    ],
    MSc: [
      "Economics with Informatics",
      "Finance",
      "Digital Marketing",
      "Procurement and Logistics",
      "Procurement and Supply Chain",
      "Human Resource Management with Informatics",
      "Economics and Public Policy",
      "Forensic Accounting",
      "Information Technology",
      "Computer Science",
    ],
  },

  KNUST: {
    BSc: [
      "Agriculture",
      "Natural Resources Management",
      "Landscape Design and Management",
      "Agricultural Biotechnology",
      "Agribusiness Management",
      "Forest Resources Technology",
      "Packaging Technology",
      "Aquaculture and Water Resources Management",
      "Architecture",
      "Construction Technology and Management",
      "Quantity Surveying and Construction Economics",
      "Development Planning",
      "Human Settlement Planning",
      "Land Economy",
      "Real Estate",
      "Fashion Design",
      "Textile Design and Technology",
      "Ceramic Technology",
      "Metal Product Design and Technology",
      "Agricultural Engineering",
      "Chemical Engineering",
      "Civil Engineering",
      "Geomatic Engineering",
      "Materials Engineering",
      "Mechanical Engineering",
      "Electrical and Electronic Engineering",
      "Computer Engineering",
      "Aerospace Engineering",
      "Petroleum Engineering",
      "Telecommunication Engineering",
      "Geological Engineering",
      "Biomedical Engineering",
      "Petrochemical Engineering",
      "Metallurgical Engineering",
      "Automobile Engineering",
      "Industrial Engineering",
      "Marine Engineering",
      "Business Administration (Human Resource Management/Management)",
      "Business Administration (Marketing/International Business)",
      "Business Administration (Accounting/Banking and Finance)",
      "Business Administration (Logistics and Supply Chain Management/Business Information Technology)",
      "Hospitality and Tourism Management",
      "Herbal Medicine",
      "Human Biology",
      "Medical Laboratory Science",
      "Medical Laboratory Technology",
      "Physiotherapy and Sports Science",
      "Medical Imaging",
      "Nursing",
      "Midwifery",
      "Disability and Rehabilitation Studies",
      "Environmental Science",
      "Biochemistry",
      "Food Science and Technology",
      "Human Nutrition",
      "Dietetics",
      "Biological Sciences",
      "Chemistry",
      "Computer Science",
      "Information Technology",
      "Mathematics",
      "Statistics",
      "Physics",
      "Actuarial Science",
      "Meteorology and Climate Science",
    ],
    BA: [
      "Akan Language and Culture",
      "Economics",
      "English",
      "French and Francophone Studies",
      "Geography and Rural Development",
      "History",
      "Linguistics",
      "Media and Communication Studies",
      "Political Studies",
      "Public Administration",
      "Religion and Human Development",
      "Sociology",
      "Social Work",
      "Communication Design (Graphic Design)",
      "Integrated Rural Art and Industry",
      "Publishing Studies",
    ],
    BFA: ["Fine Art and Curatorial Practice", "Ceramics"],
    "B.Ed.": [
      "Junior High School Education (Mathematics)",
      "Junior High School Education (Science)",
      "Junior High School Education (ICT)",
      "Junior High School Education (Agriculture Science)",
      "Junior High School Education (Visual Art)",
      "Junior High School Education (History)",
      "Junior High School Education (Geography)",
      "SHS/STEM Chemistry",
      "SHS/STEM Biology",
      "SHS/STEM Mathematics",
      "SHS/STEM Physics",
      "STEM (Aviation and Aerospace)",
      "STEM (Manufacturing)",
      "STEM (Robotics)",
      "STEM (Biomedical Science)",
      "Art and Design Technology",
    ],
    LLB: ["Law"],
    "Professional Doctorate": [
      "Doctor of Pharmacy (Pharm D)",
      "Bachelor of Dental Surgery",
      "Doctor of Veterinary Medicine (DVM)",
      "Doctor of Optometry (OD)",
    ],
  },

  "University of Ghana": {
    BSc: [
      "Actuarial Science",
      "Agricultural Engineering",
      "Agriculture",
      "Agricultural Extension",
      "Family and Consumer Science",
      "Animal Biology and Conservation Science",
      "Biochemistry, Cell and Molecular Biology",
      "Nutrition",
      "Food Science",
      "Plant and Environmental Biology",
      "Marine Science",
      "Fisheries Science",
      "Psychology",
      "Microbiology",
      "Geology",
      "Applied Geology",
      "Applied Geophysics",
      "Mathematics",
      "Statistics",
      "Biomathematics",
      "Computer Science",
      "Physics",
      "Chemistry",
      "Geophysics",
      "Computer Engineering",
      "Biomedical Engineering",
      "Food Process Engineering",
      "Materials Science and Engineering",
      "Information Technology",
      "Family and Consumer Sciences (Family and Child Studies)",
      "Family and Consumer Sciences (Food and Clothing)",
      "Business Administration",
      "Sport and Physical Culture Studies",
      "Dental Laboratory Sciences",
      "Dietetics",
      "Medical Laboratory Sciences",
      "Occupational Therapy",
      "Physiotherapy",
      "Radiography",
      "Respiratory Therapy",
      "Nursing",
      "Midwifery",
    ],
    BA: [
      "Sociology",
      "Social Work",
      "Political Science",
      "Economics",
      "Geography",
      "History",
      "English",
      "Linguistics",
      "Philosophy and Classics",
      "Study of Religions",
      "Archaeology",
      "Information Studies",
      "French",
      "Arabic",
      "Spanish",
      "Russian",
      "Swahili",
      "Chinese",
      "Theatre Arts",
      "Music",
      "Study of Ghanaian Languages",
    ],
    "B.Ed.": [
      "Engineering",
      "Information and Communication Technology",
      "Science (Physics)",
      "Science (Chemistry)",
      "Science (Biology)",
      "Mathematics",
      "Early Grade Specialism",
      "Upper-Grade Specialism",
      "JHS Specialism",
    ],
    LLB: ["Law"],
    Professional: [
      "Medicine and Surgery (MBChB)",
      "Dental Surgery",
      "Doctor of Pharmacy",
      "Veterinary Medicine",
    ],
  },

  UCC: {
    "B.Ed.": [
      "Arts",
      "Social Science",
      "Social Studies",
      "Accounting",
      "Management",
      "Science",
      "Mathematics",
      "Computer Science",
      "Health Science",
      "Health, Physical Education and Recreation",
      "Home Economics (Food and Nutrition)",
      "Home Economics (Clothing and Textile)",
      "Basic Education",
      "Early Childhood Education",
      "Psychology",
    ],
    BA: [
      "African Studies",
      "Theatre Studies",
      "Communication Studies",
      "Dance",
      "Film Studies",
      "English",
      "Social Sciences",
      "Population and Health",
      "Anthropology",
      "Social Behaviour and Conflict Management",
      "Linguistics",
    ],
    BSc: [
      "Hospitality Management",
      "Tourism Management",
      "Geography and Regional Planning",
      "Agriculture",
      "Agricultural Extension",
      "Animal Health",
      "Agribusiness",
      "Agro-Processing",
      "Agricultural Extension and Community Development",
      "Environmental Science",
      "Biochemistry",
      "Fisheries and Aquatic Science",
      "Forensic Science",
      "Molecular Biology and Biotechnology",
      "Entomology and Wildlife",
      "Computer Science",
      "Engineering Physics",
      "Industrial Chemistry",
      "Information Technology",
      "Laboratory Technology",
      "Mathematics",
      "Mathematics and Statistics",
      "Mathematics with Business",
      "Meteorology and Atmospheric Physics",
      "Mathematics with Economics",
      "Statistics",
      "Actuarial Science",
      "Chemistry",
      "Physics",
      "Water and Sanitation",
      "Nursing",
      "Mental Health Nursing",
      "Community Mental Health Nursing",
      "Biomedical Sciences",
      "Medical Laboratory Technology",
      "Clinical Nutrition and Dietetics",
      "Diagnostic Imaging Technology",
      "Diagnostic Medical Sonography",
      "Health Information Management",
      "Physician Assistant Studies",
      "Sports and Exercise Science",
      "Optometry",
      "Psychology",
    ],
    "B.Com": [
      "Accounting",
      "Finance",
      "Management",
      "Procurement and Supply Chain Management",
      "Marketing",
      "Human Resource Management",
    ],
    LLB: ["Law"],
    "B.Mus": ["Music"],
    Diploma: [
      "Basic Education",
      "Early Childhood",
      "Tourism Management",
      "Hospitality Management",
      "Labour Studies",
      "Social Behaviour and Conflict Management",
      "Microfinance",
      "Water and Sanitation",
    ],
    Professional: ["Medicine and Surgery (MBChB)"],
  },

  UPSA: {
    BSc: [
      "Agribusiness and Finance",
      "Data Science and Analytics",
      "Applied Statistics",
      "Logistics and Transport Management",
      "Accounting",
      "Accounting and Finance",
      "Business Economics",
      "Actuarial Science",
      "Banking and Finance",
      "Information Technology",
      "Applied Marketing",
      "Real Estate Management and Finance",
    ],
    BA: [
      "Applied French and Communications",
      "Communication Studies",
      "Public Relations Management",
    ],
    BBA: ["Business Administration"],
    LLB: ["Law"],
    Diploma: [
      "Accounting",
      "Marketing",
      "Management",
      "Public Relations",
      "Information Technology Management",
    ],
  },

  Ashesi: {
    BSc: [
      "Computer Science",
      "Management Information Systems",
      "Business Administration",
      "Economics",
      "Computer Engineering",
      "Electrical and Electronics Engineering",
      "Mechanical Engineering",
      "Mechatronic Engineering",
      "Bioengineering",
      "Mathematics",
      "Statistics",
      "African Studies",
      "Law and Public Policy",
    ],
  },
}

export function makeProgramKey(level: string, program: string) {
  return `${level}_${program}`
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "")
}
